import { createSlice } from '@reduxjs/toolkit';

const translationSlice = createSlice({
  name: 'translation',
  initialState: {
    language: 'en', 
    direction: 'ltr',
    translations: {
      "en": {
        "home" : "Home",
        "store" : "Store",
        "about" : "About Us",
        "brand" : "International brands",
        "blog" : "Blog",
        "contact" : "Contact Us",
        "new" : "What's new",
        "discover" : "Discover everything new",
        "detailsbtn" : "details",
        "links" : "Important links",
        "shipping" : "Shipping Information To ensure your purchases arrive safely, please be sure to provide",
        "private" : "Private Policy",
        "cookies" : "cookies Policy",
        "info" : "Delivery Information",
        "contactP" : "Contact us for any inquiries or assistance you require, we are here to provide support and advice",
        "subscribe" : "Subscribe to AdobeXD via Email",
        "login" : "Sign In",
        "register" : "Sign Up",
        "newhere" : "New Here ?",
        "welcome" : "we are glad you visited our website",
        "oneofus" : "One Of Us",
        "interested" : "You may also be interested in ",
        "track" : "Track Order" ,
        "orders" : "orders",
        "logout" : "logout" ,
        "placed" : "Placed",
        "process" : "Processing",
        "shipped" : "Shipped",
        "deliver" : "Delivered",
        "aboutParagraph" : "Your trusted partner for your health needs. We provide high-quality products and distinguished service to ensure your health and comfort. Get to know us and how we care for you",
        "buyabout" : "Buy Now",
        "accuracy" : "High accuracy",
        "accuracyParagraph" : "High accuracy guarantees you an excellent shopping experience on our e-commerce website, as we always strive to ensure the quality of our products and the accuracy of our services",
        "awards" : "awards",
        "winners" : "Winners of multiple awards, we guarantee you an exceptional shopping experience on our e-commerce website, as our  services and products are distinguished by excellence and recognition.",
        "friends" : "Friends of yours",
        "friendParagraph" : "We are your friends' place in the world of e-commerce, as we provide you with products and services that give you a unique and reliable shopping experience",
        "Fastshipping" : "Fast shipping",
        "offer" : "We offer a fast shipping service that makes your products reach you as quickly as possible, so you can enjoy an immediate and comfortable shopping experience" ,
        "addresscontact" : "Address",
        "addressdescontact" : "LAAYOUNE : MADINAT EL WAHDA BLOC B NR 91 LAAYOUNE (M).",
        "addressdescontacttwo" : "Tetouan: Mezanine bloc B Bureau n 4 BOROUJ 16 Avenue des Far N° 873 Tétouan",
        "hours" : "Working hours",
        "day" : "Monday to Friday: 7am - 7pm",
        "weekend" : "Weekend: 10am - 5pm" , 
        "phonenumber" : "phone number",
        "email" : "Email",
        "contactform" : "You are always welcome to contact us with questions, and inquiry about our services.",
        "submitcontact" : "submit message",
        "categories" : "Categories",
        "magasin" : "Store",
        "learnmore" : "Learn more through our product categories",
        "rating" : "rating",
        "price" : "price",
        "category" : "Category",
        "AllCategories" : "All Categories",
        "addtocart" : "add to cart",
        "firstname" : "First Name",
        "message" : "message",
        "save" : "save",
        "cancel" : "cancel",
        "edit" : "edit",
        "myorder" : "My Orders",
        "view" : "View and edit all your pending Delivered and Returned Orders here.",
        "orderplaced" : "Order Placed",
        "totalorder" : "Total Order",
        "totalprice" : "total price",
        "confirm" : "confirm",
        "change" : "Change Your Password",
        "choose" : "Choose a strong password and don't reuse it for other accounts.",
        "changing" : "Changing your password will sign you out of all your devices. You will need to enter your new password on all your devices.",
        "newpass" : "new password",
        "oldpass" : "current password",
        "myprofile" : "My Profile",
        "wishlist" : "Wishlist",
        "cart" : "Cart",
        "changepass" : "Change Password",
        "searchblog" : "search blog",
        "country" : "country",
        "city" : "city",
        "region" : "region",
        "street" : "street",
        "zipcode" : "zipCode",
        "all" : "All",
        "experience" : "Experience our app for a better mobile experience!",
        "download" : "Download now from the App Store or Google Play Store.",
        "aboutpro" : "about this product ",
        "productdet" : "product details" ,
        "main" : "Main Category",
        "sub" : "Sub Category" ,
        "action" : "action",
        "delete" :  "delete",
        "confirmorder" : "confirm order in this address",
        "deleteadd" : "Delete this address",
        "addaddress" : "add new address",
        "saveadd" : "Save Address",
        "orderstatus" : "Order Status" ,
        "show" : "Show Details",
        "hide" : "hide details",
        "product" : "Product",
        "quantity" : "Quantity",
        "unit" : "Unit Price",
        "total" : "Total Price",
        "clear" : "Clear Filters",
        "important" : "important links",
        "privacy" : "privacy policy",
        "terms" : "terms & conditions",
        "information" : "Information on delivery",
        "pfooter" : "Shipping Information To ensure your purchases arrive safely, please be sure to provide the correct address and telephone number to ensure a convenient and efficient shopping experience. Make sure your shipping information is up to date, including address details and desired delivery time, to ensure you receive your order quickly and without unnecessary delays.",
        "contactdetails" : "contact details",
        "require" : "Contact us for any inquiries or assistance you require, we are here to provide support and advice",
        "addfooterone" : "LAAYOUNE: MADINAT EL WAHDA BLOCK B NR 91 LAAYOUNE (M)",
        "addfootertwo" : "Tetouan: Mezanine block B Office n° 4 BOROUJ 16 Avenue des Far N° 873 Tétouan",
        "popular" : "popular products",
        "featured" : "discover what our featured products are",
      },
      "fr": {
        "home" : "Maison",
        "store" : "Magasin",
        "about" : "A propos de nous",
        "brand" : "Marques internatio",
        "blog" : "Blog",
        "contact" : "Contactez nous",
        "new" : "quoi de neuf",
        "discover" : "Découvrez tout ce qui est nouveau",
        "detailsbtn" : "détails",
        "links" : "Liens importants",
        "shipping" : "Informations d'expédition Pour garantir que vos achats arrivent sans problème, assurez-vous de fournir",
        "private" : "Politique privée",
        "cookies" : "Politique de cookies",
        "info" : "Informations sur la livraison",
        "contactP" : "Contactez-nous pour toute demande de renseignements ou d'assistance dont vous avez besoin, nous sommes là pour vous fournir soutien et conseils",
        "subscribe" : "Abonnez-vous à AdobeXD par e-mail",
        "login" : "se connecter",
        "register" : "registre",
        "newhere" : "Nouveau ici ?",
        "welcome" : "Bienvenue, nous sommes heureux que vous ayez visité notre site Web",
        "oneofus" : "Un de nous",
        "interested" : "Vous pourriez également être intéressé par",
        "track" : "suivre les commandes",
        "orders" : "ordres",
        "logout" : "Se déconnecter" ,
        "placed" : "mis",
        "process" : "Traitement",
        "shipped" : "Expédié",
        "deliver" : "Livré",
        "aboutParagraph" : "Votre partenaire de confiance pour vos besoins en santé. Nous fournissons des produits de haute qualité et un service distingué pour assurer votre santé et votre confort. Apprenez à nous connaître et comment nous prenons soin de vous",
        "buyabout" : "Acheter maintenant",
        "accuracy" : "Haute précision",
        "accuracyParagraph" : "Une haute précision vous garantit une excellente expérience d'achat sur notre site e-commerce, car nous nous efforçons toujours de garantir la qualité de nos produits et l'exactitude de nos services",
        "awards" : "Prix",
        "winners" : "Gagnants de multiples prix, nous vous garantissons une expérience d'achat exceptionnelle sur notre site e-commerce, car nos services et produits se distinguent par l'excellence et la reconnaissance.",
        "friends" : "Vos amis",
        "friendParagraph" : "Nous sommes la place de vos amis dans le monde du commerce électronique, car nous vous proposons des produits et services qui vous offrent une expérience d'achat unique et fiable.",
        "Fastshipping" : "Expédition rapide",
        "offer" : "Nous offrons un service d'expédition rapide qui permet à vos produits de vous parvenir le plus rapidement possible, afin que vous puissiez profiter d'une expérience d'achat immédiate et confortable.",
        "addresscontact" : "l'adresse",
        "addressdescontact" : "LAAYOUNE : MADINAT EL WAHDA BLOC B NR 91 LAAYOUNE (M).",
        "addressdescontacttwo" : "Tetouan: Mezanine bloc B Bureau n 4 BOROUJ 16 Avenue des Far N° 873 Tétouan",
        "hours" : "Heures de travail",
        "day" : "Du lundi au vendredi : 7h - 19h",
        "weekend" : "Weekend: 10am - 5pm" , 
        "phonenumber" : "numéro de téléphone",
        "email" : "Email",
        "contactform" : "Vous êtes toujours invités à nous contacter pour toute question ou demande de renseignements sur nos services.",
        "submitcontact" : "soumettre un message",
        "categories" : "catégories",
        "magasin" : "Magasin",
        "learnmore" : "Apprenez-en davantage à travers nos catégories de produits",
        "rating" : "notation",
        "price" : "prix",
        "category" : "catégorie",
        "AllCategories" : "toutes catégories",
        "addtocart" : "Ajouter au panier",
        "firstname" : "Prénom",
        "message" : "message",
        "save" : "enregistrer",
        "cancel" : "Annuler",
        "edit" : "modifier" ,
        "myorder" : "Mes commandes",
        "view" : "Consultez et modifiez toutes vos commandes livrées et retournées en attente ici.",
        "orderplaced" : "Commande passée",
        "totalorder" : "Commande totale",
        "totalprice" : "prix total",
        "confirm" : "confirmer",
        "change" : "Changez votre mot de passe",
        "choose" : "Choisissez un mot de passe fort et ne le réutilisez pas pour d'autres comptes.",
        "changing" : "Changer votre mot de passe vous déconnectera de tous vos appareils. Vous devrez saisir votre nouveau mot de passe sur tous vos appareils.",
        "newpass" : "nouveau mot de passe",
        "oldpass" : "Mot de passe actuel",
        "myprofile" :"Mon profil",
        "wishlist" : "liste de souhaits",
        "cart" : "Chariot",
        "changepass" : "Changer le mot de passe",
        "searchblog" : "rechercher un blog",
        "country" : "pays",
        "city" : "ville",
        "region" : "région",
        "street" : "rue",
        "zipcode" : "code postal",
        "all" : "toute",
        "experience" : "Découvrez notre application pour une meilleure expérience mobile !",
        "download" : "Télécharger maintenant depuis l'App Store ou le Google Play Store.",
        "aboutpro" : "à propos de ce produit",
        "productdet" : "détails du produit" ,
        "main" : "Catégorie principale",
        "sub" : "Sub Category",
        "action" : "action",
        "delete" :  "supprimer",
        "confirmorder" : "confirmer la commande à cette adresse",
        "deleteadd" : "Supprimer cette adresse",
        "addaddress" : "ajouter une nouvelle adresse",
        "saveadd" : "Enregistrer l'adresse",
        "orderstatus" : "Statut de la commande",
        "show" : "Afficher les détails",
        "hide" : "masquer les détails",
        "product" : "Produit",
        "quantity" : "Quantité",
        "unit" : "Prix unitaire",
        "total" : "Prix total",
        "clear" : "Effacer les filtres",
        "important" : "liens importants",
        "privacy" : "politique de confidentialité",
        "terms" : "termes et conditions",
        "information" : "Informations sur la livraison",
        "pfooter" : "Informations d'expédition Pour garantir que vos achats arrivent sans problème, assurez-vous de fournir l'adresse et le numéro de téléphone corrects pour garantir une expérience d'achat pratique et efficace. Assurez-vous que vos informations d'expédition sont à jour, y compris les détails de l'adresse et le délai de livraison souhaité, pour vous assurer de recevoir votre commande rapidement et sans retards inutiles.",
        "contactdetails" : "coordonnées",
        "require" : "Contactez-nous pour toute demande de renseignements ou d'assistance dont vous avez besoin, nous sommes là pour vous fournir soutien et conseils",
        "addfooterone" : "LAAYOUNE : MADINAT EL WAHDA BLOC B NR 91 LAAYOUNE (M)",
        "addfootertwo" :"Tétouan : Mezanine bloc B Bureau n 4 BOROUJ 16 Avenue des Far N° 873 Tétouan",
        "popular" : "produits populaires",
        "featured" : "découvrez quels sont nos produits vedettes",
      },
      "ar": {
        "home" : "الرئيسيه",
        "store" : "المتجر",
        "about" : "معلومات عنا",
        "brand" : "ماركات عالمية",
        "blog" : "المدونه",
        "contact" : "تواصل معنا",
        "new" : "ما الجديد",
        "new" : "اكتشف كل ما هو جديد",
        "detailsbtn" : "تفاصيل",
        "links" : "روابط مهمه",
        "shipping" : "معلومات الشحن لضمان وصول مشترياتك بأمان، يرجى التأكد من تقديمها",
        "private" : "سياسة خاصة",
        "cookies" : "اتفاقيات تعريف الارتباط",
        "info" : "معلومات التوصيل",
        "contactP" : "اتصل بنا للحصول على أية استفسارات أو مساعدة تحتاجها، فنحن هنا لتقديم الدعم والمشورة",
        "subscribe" : "اشترك في AdobeXD عبر البريد الإلكتروني",
        "login" : "تسجيل دخول",
        "register" : "انشاء حساب",
        "newhere" : "جديد هنا ؟",
        "welcome" : "مرحباً بك، نحن سعداء بزيارتك لموقعنا",
        "oneofus" : "واحد منا",
        "interested" : "قد تكون أيضا مهتما ب",
        "track" : "تتبع الطلب",
        "orders" : "طلبات",
        "logout" : "تسجيل خروج" ,
        "placed" : "تم الطلب",
        "process" : "معالجه",
        "shipped" : "تم الشحن",
        "deliver" : "تسليم",
        "aboutParagraph" : "شريكك الموثوق به لتلبية احتياجاتك الصحية. نحن نقدم منتجات عالية الجودة وخدمة متميزة لضمان صحتك وراحتك. تعرف علينا وكيف نهتم بك",
        "buyabout" : "اشترى الان",
        "accuracy" : "دقة عالية",
        "accuracyParagraph" : "الدقة العالية تضمن لك تجربة تسوق ممتازة على موقع التجارة الإلكترونية الخاص بنا، كما نسعى دائمًا لضمان جودة منتجاتنا ودقة خدماتنا",
        "awards" :" مكافأت" ,
        "winners" : "الفائزون بجوائز متعددة، نضمن لكم تجربة تسوق استثنائية على موقعنا للتجارة الإلكترونية، حيث تتميز خدماتنا ومنتجاتنا بالتميز والتقدير",
        "friends" : "أصدقاء لك",
        "friendParagraph" : "نحن مكان أصدقائك في عالم التجارة الإلكترونية حيث نقدم لك منتجات وخدمات تمنحك تجربة تسوق فريدة وموثوقة",
        "Fastshipping" : "شحن سريع",
        "offer" : "نحن نقدم خدمة شحن سريعة تجعل منتجاتك تصل إليك في أسرع وقت ممكن، لتستمتع بتجربة تسوق فورية ومريحة",
        "addresscontact" : "العنوان",
        "addressdescontact" : "LAAYOUNE : MADINAT EL WAHDA BLOC B NR 91 LAAYOUNE (M).",
        "addressdescontacttwo" : "Tetouan: Mezanine bloc B Bureau n 4 BOROUJ 16 Avenue des Far N° 873 Tétouan",
        "hours" : "ساعات العمل",
        "day" : "من الاثنين إلى الجمعة: 7 صباحًا - 7 مساءً",
        "weekend" : " نهاية الأسبوع: 10 صباحًا - 5 مساءً",
        "phonenumber" : "رقم الهاتف",
        "email" : "بريد الكتروني",
        "contactform" : "نرحب دائمًا باتصالك بنا لطرح الأسئلة والاستفسار عن خدماتنا.",
        "submitcontact" : "ارسال",
        "categories" : "فئات" ,
        "magasin" : "متجر",
        "learnmore" :"تعلم المزيد من خلال فئات منتجاتنا",
        "rating" : "تقييم",
        "price" : "سعر",
        "category" : "فئه",
        "AllCategories" : "جميع الفئات",
        "addtocart" : "أضف إلى السلة",
        "firstname" : "الاسم الأول",
        "message" : "رساله",
        "save" : "حفظ",
        "cancel" : "الغاء",
        "edit" : "تعديل" ,
        "myorder" : "طلباتي",
        "view" : "قم بعرض وتحرير كافة طلباتك المعلقة التي تم تسليمها وإرجاعها هنا",
        "orderplaced" : "تم تقديم الطلب",
        "totalorder" : "الطلب الإجمالي",
        "totalprice" : "السعر الكلي",
        "confirm" : "تأكيد",
        "change" : "تغيير كلمة المرور الخاصة بك",
        "choose" : "اختر كلمة مرور قوية ولا تعيد استخدامها لحسابات أخرى",
        "changing" : "سيؤدي تغيير كلمة المرور إلى تسجيل خروجك من جميع أجهزتك. ستحتاج إلى إدخال كلمة المرور الجديدة على جميع أجهزتك",
        "newpass" : "كلمة السر الجديده",
        "oldpass" : "كلمة السر الحاليه",
        "myprofile" : "ملفي الشخصي",
        "wishlist" : "قائمة الرغبات",
        "cart" : "عربة التسوق",
        "changepass" : "تغيير كلمة المرور",
        "searchblog" : "بحث" ,
        "country" : "دولة",
        "city" : "مدينه",
        "region" : "منطقه",
        "street" : "شارع",
        "zipcode" : "الرمز البريدي",
        "all" : "كل",
        "experience" : "جرّب تطبيقنا للحصول على تجربة أفضل على الهاتف المحمول",
        "download" : "قم بالتنزيل الآن من App Store أو Google Play Store.",
        "aboutpro" : "حول هذا المنتج",
        "productdet" : "تفاصيل المنتج" ,
        "main" : "الفئة الرئيسية",
        "sub" : "تصنيف فرعي" ,
        "action" : "تأكيد",
        "delete" :  "مسح",
        "confirmorder" : "تأكيد الطلب في هذا العنوان",
        "deleteadd" : "احذف هذا العنوان",
        "addaddress" : "أضف عنوانًا جديدًا",
        "saveadd" : "حفظ",
        "orderstatus" : "حالة الطلب" ,
        "show" : "اظهار التفاصيل",
        "hide" : "اخفاء التفاصيل",
        "product" : "المنتج",
        "quantity" : "الكميه",
        "unit" : "سعر الوحدة",
        "total" : "السعر الإجمالي",
        "clear" : "كل",
        "important" : "روابط هامه",
        "privacy" : "سياسة الخصوصية",
        "terms" : "الشروط والأحكام",
        "information" : "معلومات حول التسليم",
        "pfooter" : "معلومات الشحن لضمان وصول مشترياتك بأمان، يرجى التأكد من تقديم العنوان ورقم الهاتف الصحيحين لضمان تجربة تسوق مريحة وفعالة. تأكد من تحديث معلومات الشحن الخاصة بك، بما في ذلك تفاصيل العنوان ووقت التسليم المطلوب، لضمان استلام طلبك بسرعة ودون تأخير غير ضروري.",
        "contactdetails" : "معلومات شخصية",
        "require" : "اتصل بنا للحصول على أية استفسارات أو مساعدة تحتاجها، فنحن هنا لتقديم الدعم والمشورة",
        "addfooterone" : "العيون: مدينة الوحدة قطعة ب رقم 91 العيون (م)",
        "addfootertwo" : "تطوان: الميزانين كتلة ب مكتب رقم 4 البروج 16 شارع الأقصى رقم 873 تطوان",
        "popular" : "المنتجات الشعبية",
        "featured" : "اكتشف ما هي منتجاتنا المميزة",
      }
    },
  },
  reducers: {
    setLanguage: (state, action) => {
      state.language = action.payload;
      state.direction = action.payload === 'ar' ? 'rtl' : 'ltr';
    },
  },
});

export const { setLanguage } = translationSlice.actions;

export const selectLanguage = (state) => state.translation.language;
export const selectTranslations = (state) => state.translation.translations;

export default translationSlice.reducer;
